//! Which blocks exist in which Minecraft version, and the palette each
//! target gets.
//!
//! `data/block_versions.json` records, per palette block, the data version of
//! the first target it exists in (generated by `tools/gen_block_versions.py`
//! from PrismarineJS minecraft-data). A conversion for an older target never
//! chooses the block, so it never writes a name the game does not know.

use std::collections::HashMap;
use std::path::Path;
use std::sync::{Arc, Mutex};

use serde::Deserialize;

use crate::error::{Error, Result};
use crate::palette::Palette;
use crate::targets::Target;
use crate::types::ColorTable;

/// The table this build ships with.
pub const BUILTIN_JSON: &str = include_str!("../../../data/block_versions.json");

#[derive(Debug, Clone, Deserialize)]
struct Entry {
    since: i32,
}

#[derive(Debug, Clone, Deserialize)]
struct Document {
    unknown_since: i32,
    blocks: HashMap<String, Entry>,
}

/// First data version each block exists in.
#[derive(Debug, Clone)]
pub struct BlockVersions {
    since: HashMap<String, i32>,
    /// Assumed for blocks the table does not list — the newest version it
    /// was generated for, so an unlisted block is only used where it is
    /// certain to exist.
    unknown_since: i32,
}

impl BlockVersions {
    pub fn builtin() -> Self {
        Self::from_json(BUILTIN_JSON).expect("the embedded block_versions.json is valid")
    }

    pub fn from_json(text: &str) -> Result<Self> {
        let doc: Document = serde_json::from_str(text)
            .map_err(|e| Error::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e)))?;
        Ok(Self {
            since: doc.blocks.into_iter().map(|(k, v)| (k, v.since)).collect(),
            unknown_since: doc.unknown_since,
        })
    }

    pub fn load(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path).map_err(|source| Error::Read {
            path: path.to_path_buf(),
            source,
        })?;
        Self::from_json(&text)
    }

    /// Data version `block` first exists at.
    pub fn since(&self, block: &str) -> i32 {
        if block == "minecraft:air" {
            return i32::MIN;
        }
        self.since.get(block).copied().unwrap_or(self.unknown_since)
    }
    pub fn exists_in(&self, block: &str, target: &Target) -> bool {
        self.since(block) <= target.data_version
    }

    /// The part of `table` that exists in `target`.
    pub fn filter(&self, table: &ColorTable, target: &Target) -> ColorTable {
        table
            .iter()
            .filter(|(name, _)| self.exists_in(name, target))
            .map(|(name, entries)| (name.clone(), entries.clone()))
            .collect()
    }
}

/// One color table, and the palette each target gets from it — built on
/// first use and kept.
pub struct PaletteSet {
    table: ColorTable,
    versions: BlockVersions,
    /// Colors of every block in the table, for thumbnails and swatches.
    full: Palette,
    cache: Mutex<HashMap<i32, Arc<Palette>>>,
}

impl PaletteSet {
    pub fn new(table: ColorTable, versions: BlockVersions) -> Result<Self> {
        let full = Palette::from_table(&table)?;
        Ok(Self {
            table,
            versions,
            full,
            cache: Mutex::new(HashMap::new()),
        })
    }

    /// The built-in color table and block versions.
    pub fn builtin() -> Self {
        Self::new(crate::color_table::builtin(), BlockVersions::builtin())
            .expect("the embedded color table is not empty")
    }

    /// The palette for `target`: only blocks that exist there.
    pub fn for_target(&self, target: &Target) -> Result<Arc<Palette>> {
        let mut cache = self.cache.lock().expect("palette cache poisoned");
        if let Some(p) = cache.get(&target.data_version) {
            return Ok(Arc::clone(p));
        }
        let palette = Arc::new(Palette::from_table(
            &self.versions.filter(&self.table, target),
        )?);
        cache.insert(target.data_version, Arc::clone(&palette));
        Ok(palette)
    }

    /// Display color of any block in the table, whatever the target.
    pub fn color_of(&self, name: &str) -> Option<[u8; 3]> {
        self.full.color_of(name)
    }

    /// Every block in the table, as the unfiltered palette.
    pub fn full(&self) -> &Palette {
        &self.full
    }

    pub fn versions(&self) -> &BlockVersions {
        &self.versions
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::targets::TARGETS;

    fn target(id: &str) -> Target {
        Target::named(id).unwrap()
    }

    #[test]
    fn builtin_table_covers_the_palette() {
        let versions = BlockVersions::builtin();
        let table = crate::color_table::builtin();
        for name in table.keys() {
            assert!(
                versions.since.contains_key(name),
                "{name} has no version entry"
            );
        }
    }

    #[test]
    fn newer_blocks_are_gated() {
        let v = BlockVersions::builtin();
        assert!(v.exists_in("minecraft:stone", &target("1.16.5")));
        assert!(!v.exists_in("minecraft:deepslate", &target("1.16.5")));
        assert!(v.exists_in("minecraft:deepslate", &target("1.17.1")));
        assert!(!v.exists_in("minecraft:resin_block", &target("1.21.1")));
        assert!(v.exists_in("minecraft:resin_block", &target("1.21.4")));
        // Experimental in 1.20.3–1.20.6, released in 1.21.
        assert!(!v.exists_in("minecraft:tuff_bricks", &target("1.20.6")));
        assert!(v.exists_in("minecraft:tuff_bricks", &target("1.21.1")));
        assert!(v.exists_in("minecraft:air", &target("1.16.5")));
    }
    #[test]
    fn unknown_blocks_only_appear_in_the_newest_targets() {
        let v = BlockVersions::builtin();
        let newest = TARGETS.last().unwrap();
        assert!(v.exists_in("minecraft:some_future_block", newest));
        assert!(!v.exists_in("minecraft:some_future_block", &target("1.21.8")));
    }

    #[test]
    fn palettes_grow_with_the_target() {
        let set = PaletteSet::builtin();
        let mut previous = 0;
        for t in TARGETS {
            let p = set.for_target(t).unwrap();
            assert!(p.block_count() >= previous, "{} shrank", t.id);
            previous = p.block_count();
        }
        let oldest = set.for_target(&target("1.16.5")).unwrap();
        let newest = set.for_target(TARGETS.last().unwrap()).unwrap();
        assert_eq!(newest.block_count(), set.full().block_count());
        assert!(oldest.block_count() < newest.block_count());
        assert!(oldest.color_of("minecraft:resin_block").is_none());
        assert!(
            set.color_of("minecraft:resin_block").is_some(),
            "full colors stay available"
        );
    }

    #[test]
    fn palettes_are_cached_per_data_version() {
        let set = PaletteSet::builtin();
        let a = set.for_target(&target("1.20.4")).unwrap();
        let b = set.for_target(&target("1.20.4")).unwrap();
        assert!(Arc::ptr_eq(&a, &b));
    }
}
