#!/usr/bin/env python3
"""Regenerate backend/data/block_versions.json: the first target version each
palette block exists in.

    python tools/gen_block_versions.py

For every target in backend/crates/core/src/targets.rs this downloads that
version's block list from PrismarineJS minecraft-data, then records, for each
block in backend/data/color_table_safe.json, the data version of the oldest
target that has it. A conversion for an older target never uses the block.

Blocks that a version only offered behind an experimental feature flag are
moved to the release that enabled them — minecraft-data lists them from the
first snapshot, but a world without the experiment cannot place them.

Standard library only. Run it after adding a target or rebuilding the color
table, and commit the result.
"""

import json
import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGETS_RS = ROOT / "backend" / "crates" / "core" / "src" / "targets.rs"
TABLE = ROOT / "backend" / "data" / "color_table_safe.json"
OUT = ROOT / "backend" / "data" / "block_versions.json"
DATA = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data"

# Blocks shipped behind a feature flag before the release that enabled them,
# as (release data version, blocks).
EXPERIMENTAL = [
    # "Update 1.21" experiment, playable in 1.20.3–1.20.6, released in 1.21.
    (3953, [
        "polished_tuff", "tuff_bricks", "chiseled_tuff", "chiseled_tuff_bricks",
        "chiseled_copper", "exposed_chiseled_copper", "weathered_chiseled_copper",
        "oxidized_chiseled_copper", "waxed_chiseled_copper",
        "waxed_exposed_chiseled_copper", "waxed_weathered_chiseled_copper",
        "waxed_oxidized_chiseled_copper",
    ]),
]


def fetch_json(url):
    with urllib.request.urlopen(url, timeout=60) as response:
        return json.load(response)


def targets():
    """(id, data version) for every target, oldest first."""
    rows = re.findall(r'target\("([^"]+)",\s*(\d+)\)', TARGETS_RS.read_text())
    seen, out = set(), []
    for tid, dv in rows:
        if tid not in seen and tid != "custom":
            seen.add(tid)
            out.append((tid, int(dv)))
    return sorted(out, key=lambda t: t[1])


def main():
    palette = sorted(json.loads(TABLE.read_text()))
    paths = fetch_json(f"{DATA}/dataPaths.json")["pc"]
    rows = targets()

    lists, sources = [], {}
    last = None
    for tid, dv in rows:
        entry = paths.get(tid)
        if entry and "blocks" in entry:
            names = {b["name"] for b in fetch_json(f"{DATA}/{entry['blocks']}/blocks.json")}
            last = (names, entry["blocks"])
            sources[tid] = entry["blocks"]
        elif last is not None:
            # No block list for this version yet: assume the newest one known.
            names = last[0]
            sources[tid] = f"{last[1]} (carried forward)"
        else:
            sys.exit(f"no block list for {tid} and nothing older to carry forward")
        lists.append((tid, dv, names))
        print(f"{tid:>8} {dv:>5}  {len(names):>5} blocks  {sources[tid]}", file=sys.stderr)

    experimental = {f"minecraft:{b}": dv for dv, blocks in EXPERIMENTAL for b in blocks}
    blocks, problems = {}, []
    for name in palette:
        bare = name.split(":", 1)[1]
        present = [(tid, dv) for tid, dv, names in lists if bare in names]
        if not present:
            problems.append(f"{name}: in no version's block list")
            continue
        first_tid, first_dv = present[0]
        # Once a block exists it has to keep existing; a gap means a rename.
        later = [tid for tid, dv, names in lists if dv > first_dv and bare not in names]
        if later:
            problems.append(f"{name}: missing again in {', '.join(later)} — renamed?")
        since = max(first_dv, experimental.get(name, 0))
        blocks[name] = {"since": since}

    if problems:
        sys.exit("cannot generate:\n  " + "\n  ".join(problems))

    newest = rows[-1][1]
    doc = {
        "_comment": "Generated by tools/gen_block_versions.py from PrismarineJS minecraft-data. "
                    "since = data version of the first target a block exists in.",
        "sources": sources,
        "unknown_since": newest,
        "blocks": blocks,
    }
    OUT.write_text(json.dumps(doc, indent=1, sort_keys=True) + "\n")
    gated = sum(1 for b in blocks.values() if b["since"] > rows[0][1])
    print(f"{OUT.relative_to(ROOT)}: {len(blocks)} blocks, {gated} newer than {rows[0][0]}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
