#!/usr/bin/env python3
"""Generate the small glTF models the test suites convert.

    python tools/make_fixtures.py        # writes backend/fixtures/*.glb

Each model is built from primitives here, so the fixtures carry no third-party
license and can be regenerated byte for byte. They are committed; rerun this
only to change them. Needs trimesh, numpy and Pillow.
"""

import pathlib

import numpy as np
import trimesh
from PIL import Image

OUT = pathlib.Path(__file__).resolve().parent.parent / "backend" / "fixtures"


def checker(size=64, cell=8, a=(30, 120, 220), b=(240, 200, 40)):
    yy, xx = np.indices((size, size))
    img = np.zeros((size, size, 4), np.uint8)
    img[..., 3] = 255
    on = ((xx // cell + yy // cell) % 2) == 0
    img[on, :3] = a
    img[~on, :3] = b
    return Image.fromarray(img, "RGBA")


def spherical_uv(vertices):
    return np.column_stack([
        (np.arctan2(vertices[:, 0], vertices[:, 2]) / (2 * np.pi)) % 1.0,
        (vertices[:, 1] / np.abs(vertices[:, 1]).max() + 1) / 2,
    ])


def textured():
    """A checker-textured sphere beside a plain red box: two primitives, a
    texture and an untextured baseColorFactor."""
    sphere = trimesh.creation.uv_sphere(radius=1.0, count=[32, 32])
    sphere.visual = trimesh.visual.TextureVisuals(
        uv=spherical_uv(sphere.vertices),
        material=trimesh.visual.material.PBRMaterial(baseColorTexture=checker()),
    )
    box = trimesh.creation.box(extents=[0.8, 0.8, 0.8])
    box.apply_translation([1.4, 0.0, 0.0])
    box.visual = trimesh.visual.TextureVisuals(
        material=trimesh.visual.material.PBRMaterial(baseColorFactor=[0.9, 0.1, 0.1, 1.0]))
    return trimesh.Scene([sphere, box])


def vertex_colors():
    """A torus colored per vertex by its angle around the ring."""
    torus = trimesh.creation.torus(major_radius=1.0, minor_radius=0.35,
                                   major_sections=48, minor_sections=16)
    angle = (np.arctan2(torus.vertices[:, 2], torus.vertices[:, 0]) / (2 * np.pi)) % 1.0
    rgb = np.column_stack([
        0.5 + 0.5 * np.cos(2 * np.pi * angle),
        0.5 + 0.5 * np.cos(2 * np.pi * (angle - 1 / 3)),
        0.5 + 0.5 * np.cos(2 * np.pi * (angle - 2 / 3)),
    ])
    colors = np.column_stack([(rgb * 255).round(), np.full(len(rgb), 255)]).astype(np.uint8)
    torus.visual = trimesh.visual.ColorVisuals(mesh=torus, vertex_colors=colors)
    return trimesh.Scene([torus])


def metal_and_transforms():
    """Polished and rough metal spheres on a textured slab, placed through
    rotated and scaled scene nodes rather than baked vertices."""
    scene = trimesh.Scene()
    slab = trimesh.creation.box(extents=[3.0, 0.2, 1.5])
    uv = np.column_stack([(slab.vertices[:, 0] + 1.5) / 3.0, (slab.vertices[:, 2] + 0.75) / 1.5])
    slab.visual = trimesh.visual.TextureVisuals(
        uv=uv, material=trimesh.visual.material.PBRMaterial(baseColorTexture=checker(cell=16)))
    scene.add_geometry(slab, node_name="slab",
                       transform=trimesh.transformations.rotation_matrix(np.radians(10), [0, 1, 0]))
    for i, roughness in enumerate([0.05, 0.9]):
        ball = trimesh.creation.icosphere(subdivisions=3, radius=0.5)
        ball.visual = trimesh.visual.TextureVisuals(material=trimesh.visual.material.PBRMaterial(
            baseColorFactor=[0.8, 0.6, 0.2, 1.0], metallicFactor=1.0, roughnessFactor=roughness))
        place = trimesh.transformations.compose_matrix(
            scale=[1.0, 1.3, 1.0], translate=[-0.8 + 1.6 * i, 0.7, 0.0])
        scene.add_geometry(ball, node_name=f"ball{i}", transform=place)
    return scene


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, build in [("textured", textured), ("vertex_colors", vertex_colors),
                        ("metal_transforms", metal_and_transforms)]:
        path = OUT / f"{name}.glb"
        path.write_bytes(build().export(file_type="glb"))
        print(f"{path.relative_to(OUT.parent.parent)}  {path.stat().st_size} bytes")


if __name__ == "__main__":
    main()
